/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chat_app.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>

char* chat = NULL;

int* writemsg_1_svc(char** argp, struct svc_req *rqstp) {
 	static int  result;

	if (chat == NULL) {
		chat = (char*)malloc(sizeof(char) * (strlen(*argp) + 1));
		strcpy(chat, *argp);
	} else {
		int len_argp = strlen(*argp);
		int len_chat = strlen(chat);
		chat = realloc(chat, sizeof(char) * (len_chat + len_argp + 1));
		strcat(chat, *argp);
	}
 	return &result;

	result = 1;

	return &result;
}

char** getchat_1_svc(void *argp, struct svc_req *rqstp) {
	static char* result;
	if (chat == NULL) {
		result = "";
	} else {
		result = chat;
	}
	return &result;
}
