/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_APP_H_RPCGEN
#define _CHAT_APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CHAT_APP 0x12341111
#define VERSION_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define writeMsg 1
extern  int * writemsg_1(char **, CLIENT *);
extern  int * writemsg_1_svc(char **, struct svc_req *);
#define getChat 2
extern  char ** getchat_1(void *, CLIENT *);
extern  char ** getchat_1_svc(void *, struct svc_req *);
extern int chat_app_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define writeMsg 1
extern  int * writemsg_1();
extern  int * writemsg_1_svc();
#define getChat 2
extern  char ** getchat_1();
extern  char ** getchat_1_svc();
extern int chat_app_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_APP_H_RPCGEN */
