/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chatapp.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif


#include "chatapp.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

// A simple structure to hold our chat history
struct {
    message messages[1000];
    int count;
} chat_history;

chat_history * get_chat_history_1_svc(void *argp, struct svc_req *rqstp)
{
    static chat_history result;

    // Just return our chat history
    result = chat_history;

    return &result;
}

int * send_message_1_svc(message *argp, struct svc_req *rqstp)
{
    static int result;

    // Check if we have room for more messages
    if (chat_history.count >= 1000) {
        result = 0; // Indicate failure
    } else {
        // Add the new message to our chat history
        chat_history.messages[chat_history.count] = *argp;
        chat_history.count++;
        result = 1; // Indicate success
    }

    return &result;
}


static void
chatapp_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		message send_message_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case get_chat_history:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_chat_history;
		local = (char *(*)(char *, struct svc_req *)) get_chat_history_1_svc;
		break;

	case send_message:
		_xdr_argument = (xdrproc_t) xdr_message;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) send_message_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CHATAPP, VER1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CHATAPP, VER1, chatapp_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CHATAPP, VER1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CHATAPP, VER1, chatapp_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CHATAPP, VER1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
