/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chatapp.h"

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->sender, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->content, 500))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chat_history (XDR *xdrs, chat_history *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->messages.messages_val, (u_int *) &objp->messages.messages_len, 1000,
		sizeof (message), (xdrproc_t) xdr_message))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}
